force-app/main/default/objects/Assigne_ressource__c/Assigne_ressource__c.object-meta.xml
<CustomObject>
    <label>Assigne task</label>
    <nameField>
        <label>Assigne ressource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assigne tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assigne_ressource__c/fields/Ressource__c.field-meta.xml
<CustomField>
    <fullName>Ressource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ressource</label>
    <referenceTo>Ressource__c</referenceTo>
    <relationshipLabel>Assigne tasks</relationshipLabel>
    <relationshipName>Assigne_tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assigne_ressource__c/fields/task__c.field-meta.xml
<CustomField>
    <fullName>task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>task</label>
    <referenceTo>Task__c</referenceTo>
    <relationshipLabel>Assigne tasks</relationshipLabel>
    <relationshipName>Assigne_tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Projet__c/Projet__c.object-meta.xml
<CustomObject>
    <label>Projet</label>
    <nameField>
        <label>Projet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Projet__c/fields/Start_date__c.field-meta.xml
<CustomField>
    <fullName>Start_date__c</fullName>
    <description>When the project Start</description>
    <label>Start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ressource__c/Ressource__c.object-meta.xml
<CustomObject>
    <label>Ressource</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ressource</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ressource__c/fields/Hiring_date__c.field-meta.xml
<CustomField>
    <fullName>Hiring_date__c</fullName>
    <label>Hiring date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ressource__c/fields/Prenom__c.field-meta.xml
<CustomField>
    <fullName>Prenom__c</fullName>
    <label>First Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task Projet</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Commentaire__c.field-meta.xml
<CustomField>
    <fullName>Commentaire__c</fullName>
    <label>Commentaire</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Due_Time__c.field-meta.xml
<CustomField>
    <fullName>Due_Time__c</fullName>
    <label>Due Time</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
                <default>true</default>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Urgent</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/fields/Projet__c.field-meta.xml
<CustomField>
    <fullName>Projet__c</fullName>
    <label>Projet</label>
    <referenceTo>Projet__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Ressource__c.field-meta.xml
<CustomField>
    <fullName>Ressource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ressource</label>
    <referenceTo>Ressource__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/projectManagerCtl.cls
public with sharing class projectManagerCtl {
  
    //this method is use to retrive all datas releted to the project 
    @AuraEnabled(cacheable=true)
    public static Map<String,Object> getTask(String recordId){
        try {
            Projet__c p;
            List<Ressource__c> rss = new List<Ressource__c>();
            List<Assigne_ressource__c> assTask= new List<Assigne_ressource__c>();
            Set<String> resourceIds = new Set<String>(); 
            Map<Id,Task__c> Tasks; 
            p =  [SELECT id,name FROM Projet__c WHERE id =:recordId];
            Tasks = new Map<Id,Task__c>([SELECT Id,Name, Projet__c, Status__c, Priority__c, Commentaire__c, Due_Time__c , Start_date__c, End_date__c FROM Task__c WHERE Projet__c =: p.id]);
            assTask = [SELECT id, task__c,Ressource__c  FROM Assigne_ressource__c WHERE task__c IN : Tasks.keySet()];
            rss =[SELECT id, Prenom__c,Name , Hiring_date__c, Phone__c, Email__c FROM Ressource__c ORDER BY CreatedDate];
           
            return new Map<String,Object>{'p'=>p,'Tasks'=>Tasks.values(),'assTask'=>assTask,'allrss'=>rss};
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

     /*
    *************************************************************************************************************
    * Below method is issed to get the picklist value.
    *************************************************************************************************************
    */
    @AuraEnabled(cacheable=true)
    public static List<String> getTaskPicklist()
    {
        List<String> pickListValuesList= new List<String>();
		Schema.DescribeFieldResult fieldResult = Task__c.Status__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
			pickListValuesList.add(pickListVal.getLabel());
		}     
		return pickListValuesList;
    }

  
}